name: "Autodeploy"

on:
  schedule:
    # deploy every day at an off-schedule
    - cron: "30 9 * * *"

jobs:
  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
